2025-02-09 20:08:30,533:DEBUG:certbot._internal.main:certbot version: 3.1.0
2025-02-09 20:08:30,533:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2025-02-09 20:08:30,533:DEBUG:certbot._internal.main:Arguments: ['--standalone', '-d', '5.101.180.12:8443', '--non-interactive', '--agree-tos', '--disable-hook-validation', '-m', 'lazarev_a@auca.kg']
2025-02-09 20:08:30,534:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-02-09 20:08:30,553:DEBUG:certbot._internal.log:Root logging level set at 30
2025-02-09 20:08:30,556:DEBUG:certbot._internal.plugins.selection:Requested authenticator standalone and installer None
2025-02-09 20:08:30,557:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * standalone
Description: Runs an HTTP server locally which serves the necessary validation files under the /.well-known/acme-challenge/ request path. Suitable if there is no HTTP server already running. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='standalone', value='certbot._internal.plugins.standalone:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x7edf160009e0>
Prep: True
2025-02-09 20:08:30,557:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.standalone.Authenticator object at 0x7edf160009e0> and installer None
2025-02-09 20:08:30,557:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2025-02-09 20:08:30,629:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-02-09 20:08:30,634:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2025-02-09 20:08:31,089:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 828
2025-02-09 20:08:31,089:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 09 Feb 2025 20:08:31 GMT
Content-Type: application/json
Content-Length: 828
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "6LmtnzYYi7c": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "The same profile you're accustomed to"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2025-02-09 20:08:31,090:DEBUG:acme.client:Requesting fresh nonce
2025-02-09 20:08:31,090:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-02-09 20:08:31,241:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2025-02-09 20:08:31,242:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 09 Feb 2025 20:08:31 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: A-S0uJjSiB44ws0M3kpgOOCsFeLZGW_pwNV-lopJZBJS6Z8yqVM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-02-09 20:08:31,242:DEBUG:acme.client:Storing nonce: A-S0uJjSiB44ws0M3kpgOOCsFeLZGW_pwNV-lopJZBJS6Z8yqVM
2025-02-09 20:08:31,243:DEBUG:acme.client:JWS payload:
b'{\n  "contact": [\n    "mailto:lazarev_a@auca.kg"\n  ],\n  "termsOfServiceAgreed": true\n}'
2025-02-09 20:08:31,251:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-acct:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAiandrIjogeyJuIjogIjFLNi0zSXBNX0tvdjVHVldtTTdQY1A2dllWMFkzdmgyc2pHQm9WUFRFcmpvb0xUdUpwMVh2QmJtUkdiSTlsQzBzSGR5WkxSRVV1Nl96VHNoU0dxZWtxVW1ab1FVODd1RW1qWDJsSkVRX216RHlvSlpST3ZLRmM0ZnBSdzRpNVJVUnZGa0lrdjVxbmhqSXJfTm5uUGVsWW1SRTNRX1g4eTlFajlaTTBUVWdDelNybHpZZ1JVY3ZoUGtwZ2gyQTFfRFdtajR6UVMxNlFtYlJpeU5DZFhnUGJpX2dEM1RsTnlQTVJ4eWVCZ1c4MzlYbjZ4S2pVQlRGRGNaYnhQa21SR3RYcWkxZ2ptY2hpaXhlSTF2QVFhNjVCMWJoTlFJSFdHNFE4eTRwYzhCNHZnRklfMTY1ZEI2MHhoajB5V0cwYjMwd1ZUU0p0czI0Tno1N0V2VmhNZTE1dyIsICJlIjogIkFRQUIiLCAia3R5IjogIlJTQSJ9LCAibm9uY2UiOiAiQS1TMHVKalNpQjQ0d3MwTTNrcGdPT0NzRmVMWkdXX3B3TlYtbG9wSlpCSlM2Wjh5cVZNIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctYWNjdCJ9",
  "signature": "Gmwqp64miSUxVnvW_BgW6ssBdbUdU-vX0kfMlQG_0pxZOXIIbENVM_2Wbhsi-BPLTXxWj44N6KlA_bbTTcdzIfVnuPw_1JI4C1zNhvoUeOu_nlDeiLK7ZrW4bwP9d5wXQG9k451K0QyV0mUPy8y7XpED4S2zhUdZYNKzGWxhkb43kuRipjNATrftMy6xH4aIWowD3lFtfVUKgW0Hh_GYbY7RAQ-CrsfXrc-IByfcbuQbfGrkWl1ofqhYYrhD8x7a_tM2IgSujmiZN6ULnHxIcXuDMRPWaZgn0yOQWNHvdQvULLemAI45TenrnpUIsXKnFAjhWSVTiyuKooGhTCV7hQ",
  "payload": "ewogICJjb250YWN0IjogWwogICAgIm1haWx0bzpsYXphcmV2X2FAYXVjYS5rZyIKICBdLAogICJ0ZXJtc09mU2VydmljZUFncmVlZCI6IHRydWUKfQ"
}
2025-02-09 20:08:31,451:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-acct HTTP/1.1" 201 528
2025-02-09 20:08:31,452:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sun, 09 Feb 2025 20:08:31 GMT
Content-Type: application/json
Content-Length: 528
Connection: keep-alive
Boulder-Requester: 2219103505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf>;rel="terms-of-service"
Location: https://acme-v02.api.letsencrypt.org/acme/acct/2219103505
Replay-Nonce: ES_SC8yEPcW4UIWIh5qwGrDdnLuW4FAae9JyYo0LsCzIpBi2d8U
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "key": {
    "kty": "RSA",
    "n": "1K6-3IpM_Kov5GVWmM7PcP6vYV0Y3vh2sjGBoVPTErjooLTuJp1XvBbmRGbI9lC0sHdyZLREUu6_zTshSGqekqUmZoQU87uEmjX2lJEQ_mzDyoJZROvKFc4fpRw4i5RURvFkIkv5qnhjIr_NnnPelYmRE3Q_X8y9Ej9ZM0TUgCzSrlzYgRUcvhPkpgh2A1_DWmj4zQS16QmbRiyNCdXgPbi_gD3TlNyPMRxyeBgW839Xn6xKjUBTFDcZbxPkmRGtXqi1gjmchiixeI1vAQa65B1bhNQIHWG4Q8y4pc8B4vgFI_165dB60xhj0yWG0b30wVTSJts24Nz57EvVhMe15w",
    "e": "AQAB"
  },
  "contact": [
    "mailto:lazarev_a@auca.kg"
  ],
  "createdAt": "2025-02-09T20:08:31.374165029Z",
  "status": "valid"
}
2025-02-09 20:08:31,452:DEBUG:acme.client:Storing nonce: ES_SC8yEPcW4UIWIh5qwGrDdnLuW4FAae9JyYo0LsCzIpBi2d8U
2025-02-09 20:08:31,454:DEBUG:certbot._internal.display.obj:Notifying user: Account registered.
2025-02-09 20:08:31,455:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.bindings._rust.openssl.rsa.RSAPublicKey object at 0x7edf15ca4550>)>), contact=('mailto:lazarev_a@auca.kg',), agreement=None, status='valid', terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2219103505', new_authzr_uri=None, terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf'), 5419752d9ebef24cc83ce73e327da5c0, Meta(creation_dt=datetime.datetime(2025, 2, 9, 20, 8, 31, tzinfo=<UTC>), creation_host='abe4a56e3107', register_to_eff=None))>
2025-02-09 20:08:31,457:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for 5.101.180.12:8443
2025-02-09 20:08:31,461:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "5.101.180.12:8443"\n    }\n  ]\n}'
2025-02-09 20:08:31,463:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjIxOTEwMzUwNSIsICJub25jZSI6ICJFU19TQzh5RVBjVzRVSVdJaDVxd0dyRGRuTHVXNEZBYWU5SnlZbzBMc0N6SXBCaTJkOFUiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "xLFOvUrpN9-klPIqISSHSTsfJGjmY2Nmd_NIXr3xEJzU-3sIjoqdPWA4vlY_kwhZkU6xsfPgp49HGPaRZqKRvuQXTEziDe4FiTAdzzGWNpVgjtZC_1i2iOvqJNW-UZG9RwczT2MolfU5bNypl9qeQspmeoYhVsGYP9T2sE05d2cgxERsWHu5CxLwZXG48gWWVHMkDweTiFV4eEN-u-BDcUa6nLOn2OgkOpC3qwLtHNXwGtaiaZXyhUpr8wDfu0d-SIv3mqKlyOrrpXFFoCpte1EY7otOYvHNPnm-rUM8fWMkKLOCyRnKID6YtAE60EyVj1j7R6JtwTNW8-xmukSjvQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIjUuMTAxLjE4MC4xMjo4NDQzIgogICAgfQogIF0KfQ"
}
2025-02-09 20:08:31,618:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 400 208
2025-02-09 20:08:31,619:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Date: Sun, 09 Feb 2025 20:08:31 GMT
Content-Type: application/problem+json
Content-Length: 208
Connection: keep-alive
Boulder-Requester: 2219103505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: ES_SC8yEaXGLN5xtxKDD1vnNGdJbMk2YMAbZZR0y_YlFvpyLHjM

{
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Invalid identifiers requested :: Cannot issue for \"5.101.180.12:8443\": Domain name contains an invalid character",
  "status": 400
}
2025-02-09 20:08:31,619:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1873, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1579, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 518, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 429, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 479, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 142, in new_order
    response = self._post(self.directory['newOrder'], order)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 370, in _post
    return self.net.post(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 743, in post
    return self._post_once(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 756, in _post_once
    response = self._check_response(response, content_type=content_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 607, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rejectedIdentifier :: The server will not issue certificates for the identifier :: Invalid identifiers requested :: Cannot issue for "5.101.180.12:8443": Domain name contains an invalid character
2025-02-09 20:08:31,628:ERROR:certbot._internal.log:An unexpected error occurred:
2025-02-09 20:08:31,629:ERROR:certbot._internal.log:Invalid identifiers requested :: Cannot issue for "5.101.180.12:8443": Domain name contains an invalid character
